version: '3'
services:
  app:
    build:
      context: .
    environment:
      - profile=local-docker
    container_name: "global-api"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./docker/volumes/postgres/volumes:/var/lib/postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
  redis:
    image: redis
    ports:
      - "6379:6379"
