version: '2'
services:
  db:
    image: postgres:10
    ports:
      - "3306:3306"
    volumes:
      - ./docker/postgres/volumes:/var/lib/postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
  redis:
    image: redis
    ports:
      - "6379:6379"
