version: '2'
services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./docker/volumes/postgres/volumes:/var/lib/postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
  redis:
    image: redis
    ports:
      - "6379:6379"
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
