# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sb
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  messages:
    basename: i18n/messages
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
doma:
  dialect: postgres
flyway:
  enabled: true
