# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  data:
     rest:
      basePath: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/sb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  messages:
    basename: i18n/messages
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
#flyway:
  #enabled: true
